name: Sean Hamilton - Portrait and Commercial Photographer
favicon: null
layout_spectrum: 0.10755
typography_spectrum: 0.18477341928519309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
